using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using StudentManagementSystemShared.Dtos;

public class ReportCardPdfService
{
	public byte[] Generate(StudentReportCardDto data)
	{
		var subjects = data.Subjects ?? new List<SubjectResultDto>();

		return Document.Create(document =>
		{
			document.Page(page =>
			{
				page.Size(PageSizes.A4);
				page.Margin(20);
				page.DefaultTextStyle(x => x.FontSize(10));

				page.Header()
					.Element(container => BuildHeader(container, data));

				page.Content()
					.PaddingTop(10)
					.Row(row =>
					{
						// LEFT SIDE
						row.RelativeItem(7)
							.Element(container =>
							{
								BuildLeftColumn(container, data);
							});

						row.ConstantItem(180)
							.Element(container =>
							{
								BuildRightColumn(container, data);
							});
					});

				page.Footer()
				    .PaddingTop(6)
					.AlignCenter()
					.Text("Generated by Student Management System")
					.FontSize(9)
					.Italic();
			});

		}).GeneratePdf();
	}

	//======================================================
	// HEADER
	//======================================================

	private void BuildHeader(IContainer container, StudentReportCardDto data)
	{
		container.Column(column =>
		{
			column.Item().AlignCenter().Text("SCHOOL REPORT CARD")
				.Bold()
				.FontSize(20);

			column.Item()
				.AlignCenter()
				.Text(data.SchoolName ?? "School Management System")
				.Bold()
				.FontSize(16);

			if (!string.IsNullOrWhiteSpace(data.SchoolAddress))
			{
				column.Item()
					.AlignCenter()
					.Text(data.SchoolAddress)
					.FontSize(9);
			}

			column.Item().PaddingTop(8);

			column.Item().Text($"Continuous Assessment For: {data.StudentName}");

			column.Item().PaddingTop(5);

			column.Item().Row(row =>
			{
				row.RelativeItem()
					.Text($"Class: {data.ClassName}");

				row.RelativeItem()
					.Text($"Term: {data.Term}");

				row.RelativeItem()
					.AlignRight()
					.Text($"Session: {data.Session}");
			});

			column.Item().PaddingBottom(10);
		});
	}

	//======================================================
	// MAIN BODY
	//======================================================

	private void BuildLeftColumn(IContainer container, StudentReportCardDto data)
	{
		container.Column(column =>
		{
			column.Item()
				.Element(x => BuildSubjectsTable(x, data));

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(x => BuildSummarySection(x, data));
			column.Item()
				.Element(BuildCommentSection);
		});
	}

	private void BuildRightColumn(IContainer container, StudentReportCardDto data)
	{
		container.Column(column =>
		{
			column.Item()
				.Element(BuildPsychomotorSection);

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(BuildAffectiveSection);

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(BuildGradeLegend);

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(BuildAttendanceSection);

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(BuildPunctualityScale);

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(BuildTermSection);

			column.Item()
				.PaddingTop(2);

			

			column.Item()
				.PaddingTop(2);

			column.Item()
				.Element(BuildStampSection);
		});
	}

	//======================================================
	// PLACEHOLDERS
	//======================================================

	private void BuildSubjectsTable(IContainer container, StudentReportCardDto data)
	{
		var subjects = data.Subjects ?? new List<SubjectResultDto>();

		container.Border(1).Table(table =>
		{
			table.ColumnsDefinition(columns =>
			{
				columns.RelativeColumn(4);
				columns.ConstantColumn(35);
				columns.ConstantColumn(35);
				columns.ConstantColumn(40);
				columns.ConstantColumn(35);
				columns.ConstantColumn(40);
				columns.ConstantColumn(35);
			});

			table.Header(header =>
			{
				header.Cell().Element(HeaderStyle).Text("SUBJECT").Bold().FontSize(8);
				header.Cell().Element(HeaderStyle).Text("TEST").Bold().FontSize(8);
				header.Cell().Element(HeaderStyle).Text("TEST").Bold().FontSize(8);
				header.Cell().Element(HeaderStyle).Text("ASS").Bold().FontSize(8);
				header.Cell().Element(HeaderStyle).Text("EXAM").Bold().FontSize(8);
				header.Cell().Element(HeaderStyle).Text("TOTAL").Bold().FontSize(8);
				header.Cell().Element(HeaderStyle).Text("GRADE").Bold().FontSize(8);
			});

			foreach (var subject in subjects)
			{
				BodyCell(table, subject.Subject);
				BodyCell(table, subject.Test1.ToString());
				BodyCell(table, subject.Test2.ToString());
				BodyCell(table, subject.Assignment.ToString());
				BodyCell(table, subject.Exam.ToString());
				BodyCell(table, subject.Total.ToString());
				BodyCell(table, subject.Grade);
			}

			int remaining = Math.Max(0, 18 - subjects.Count);

			for (int i = 0; i < remaining; i++)
			{
				for (int j = 0; j < 7; j++)
					BodyCell(table, "");
			}
		});
	}

	private void BuildSummarySection(IContainer container, StudentReportCardDto data)
	{
		container.Column(column =>
		{
			column.Item().PaddingTop(5);
			SummaryField(column, "OVERALL TOTAL", "");

			SummaryField(column, "TOTAL SCORED", "");

			SummaryField(column, "PERCENTAGE", "");

			SummaryField(column, "NO OF STUDENT IN THE CLASS", "");

			SummaryField(column, "POSITION", "");

			SummaryField(column, "PASSES/FAILED", "");

			SummaryField(column, "CLASS TEACHER REMARKS", "");

			SummaryField(column, "SIGNATURE AND DATE", "");


			SummaryField(column, "RECEIVED REPORT CARD OF MY CHILD FOR", "");

			column.Item().PaddingTop(8);

			
		});
	}

	private void BuildPsychomotorSection(IContainer container)
	{
		var skills = new[]
		{
		"Verbal Fluency",
		"Sports/Games",
		"Writing",
		"Handling Tools",
		"Drawing/Painting",
		"Musical Skills"
	};

		container.Border(1).Table(table =>
		{
			table.ColumnsDefinition(columns =>
			{
				columns.RelativeColumn(3);

				for (int i = 0; i < 5; i++)
					columns.ConstantColumn(18);
			});

			// Header
			table.Cell().Border(1).Padding(2)
				.Text("Psycho Motor Skill")
				.FontSize(7)
				.Bold();

			for (int i = 5; i >= 1; i--)
			{
				table.Cell()
					.Border(1)
					.AlignCenter()
					.AlignMiddle()
					.Text(i.ToString())
					.FontSize(7)
					.Bold();
			}

			// Rows
			foreach (var skill in skills)
			{
				table.Cell()
					.Border(1)
					.Padding(2)
					.Text(skill)
					.FontSize(7);

				for (int i = 0; i < 5; i++)
				{
					table.Cell()
						.Border(1)
						.Height(18);
				}
			}
		});
	}

	private void BuildAffectiveSection(IContainer container)
	{
		var traits = new[]
		{
		"Neatness",
		"Politeness",
		"Honesty",
		"Helping Others",
		"Emotional Stability",
		"Attitude To School Work",
		"Attentiveness In Class"
	};

		container.Border(1).Table(table =>
		{
			table.ColumnsDefinition(columns =>
			{
				columns.RelativeColumn(3);

				for (int i = 0; i < 5; i++)
					columns.ConstantColumn(18);
			});

			// Header
			table.Cell().Border(1).Padding(2)
				.Text("Affection Area")
				.FontSize(7)
				.Bold();

			for (int i = 5; i >= 1; i--)
			{
				table.Cell()
					.Border(1)
					.AlignCenter()
					.AlignMiddle()
					.Text(i.ToString())
					.FontSize(7)
					.Bold();
			}

			// Rows
			foreach (var item in traits)
			{
				table.Cell()
					.Border(1)
					.Padding(2)
					.Text(item)
					.FontSize(7);

				for (int i = 0; i < 5; i++)
				{
					table.Cell()
						.Border(1)
						.Height(18);
				}
			}
		});
	}

	private void BuildGradeLegend(IContainer container)
	{
		container.PaddingLeft(5).Column(column =>
		{
			column.Item()
				.Text("3.   GRADES")
				.Bold()
				.FontSize(8);

			GradeRow(column, "0", "39", "F9", "Fail");
			GradeRow(column, "40", "44", "F9", "Poor");
			GradeRow(column, "45", "49", "P7", "Fair");
			GradeRow(column, "50", "54", "C4", "Pass");
			GradeRow(column, "55", "59", "C5", "Good");
			GradeRow(column, "60", "64", "C4", "Good");
			GradeRow(column, "65", "69", "A1", "Very Good");
			GradeRow(column, "70", "74", "A1", "Excellent");
			GradeRow(column, "75", "Above", "A1", "Excellent");
		});
	}

	private void GradeRow(
		ColumnDescriptor column,
		string from,
		string to,
		string grade,
		string remark)
	{
		column.Item().Row(row =>
		{
			row.ConstantItem(20).Text(from).FontSize(7);

			row.ConstantItem(10)
				.AlignCenter()
				.Text("-")
				.FontSize(7);

			row.ConstantItem(30).Text(to).FontSize(7);

			row.ConstantItem(25)
				.AlignCenter()
				.Text(grade)
				.FontSize(7);

			row.RelativeItem()
				.AlignRight()
				.Text(remark)
				.FontSize(7);
		});
	}

	private void BuildAttendanceSection(IContainer container)
	{
		container
			.Border(1)
			.Padding(4)
			.Column(column =>
			{
				column.Item()
					.Text("4.   PUNCTUALITY AND REGULARITY")
					.Bold()
					.FontSize(8);

				AttendanceLine(column, "No of Times Schools Opened");
				AttendanceLine(column, "No of Times Present");
				AttendanceLine(column, "No of Times Punctual");
				AttendanceLine(column, "No in Class");
				AttendanceLine(column, "Class Av. ATT");
				AttendanceLine(column, "TERM ATT");
			});
	}

	private void AttendanceLine(ColumnDescriptor column, string text)
	{
		column.Item()
			.PaddingTop(3)
			.Row(row =>
			{
				row.RelativeItem()
					.Text($"{text} __________________")
					.FontSize(7);
			});
	}
	private void BuildPunctualityScale(IContainer container)
	{
		container.Column(column =>
		{
			column.Item()
				.Text("5.   PUNCTUALITY AND REGULARITY")
				.Bold()
				.FontSize(8);

			column.Item().Text("5. Excellent").FontSize(7);

			column.Item().Text("4. Good").FontSize(7);

			column.Item().Text("3. Fair").FontSize(7);

			column.Item().Text("2. Poor").FontSize(7);

			column.Item().Text("1. Very Poor").FontSize(7);
		});
	}
	private void BuildTermSection(IContainer container)
	{
		container.Column(column =>
		{
			column.Item()
				.Border(1)
				.Padding(5)
				.Text("Term Ending")
				.FontSize(8);

			column.Item()
				.Border(1)
				.Padding(5)
				.Text("Next Term Begins")
				.FontSize(8);
		});
	}
	private void BuildCommentSection(IContainer container)
	{
		container.Column(column =>
		{
			column.Item()
				.PaddingTop(20)
				.Text("HEAD TEACHER'S COMMENTS")
				.Bold()
				.FontSize(8);

			column.Item()
				.BorderBottom(1)
				.Height(20);


			column.Item()
				.PaddingTop(8)
				.Text("H/M'S SIGNATURE / DATE")
				.Bold()
				.FontSize(8);

			column.Item()
				.BorderBottom(1)
				.Height(20);

			column.Item().PaddingTop(40)
	.Width(160)
	.BorderBottom(1)
	.Height(20);

			column.Item()
				.PaddingTop(10)
				.Text("PARENT'S/GUARDIAN'S SIGNATURE")
				.Bold()
				.FontSize(8);


		});
	}

	private void BuildStampSection(IContainer container)
	{
		container.Column(column =>
		{
			column.Item()
				.BorderBottom(1)
				.Height(35);
			column.Item()
				.PaddingTop(10)
				.Text("SCHOOL'S STAMP AND SIGNATURE")
				.Bold()
				.FontSize(8);

			
		});
	}
	//helper methods
	private static IContainer HeaderStyle(IContainer container)
	{
		return container
			.Border(1)
			.Background(Colors.Grey.Lighten3)
			.Padding(3)
			.AlignCenter()
			.AlignMiddle();
	}
	private void BodyCell(TableDescriptor table, string value)
	{
		table.Cell()
			.Border(1)
			.Padding(3)
			.AlignCenter()
			.AlignMiddle()
			.Text(value ?? "")
			.FontSize(8);
	}

	private void SummaryRow(ColumnDescriptor column, string title, string value)
	{
		column.Item().Row(row =>
		{
			row.RelativeItem()
				.Text(title)
				.FontSize(8);

			row.ConstantItem(50)
				.AlignRight()
				.Text(value)
				.Bold()
				.FontSize(8);
		});

		column.Item().LineHorizontal(0.5f);
	}
	private void SummaryField(ColumnDescriptor column, string title, string value)
	{
		column.Item().Row(row =>
		{
			row.RelativeItem(4)
				.Text(title)
				.FontSize(8);

			row.RelativeItem(2)
				.BorderBottom(0.5f)
				.AlignRight()
				.Text(value)
				.Bold()
				.FontSize(8);
		});

		column.Item().PaddingBottom(3);
	}
	private void GradeRow(ColumnDescriptor column, string score, string grade)
	{
		column.Item().Row(row =>
		{
			row.RelativeItem().Text(score).FontSize(8);

			row.ConstantItem(25)
				.AlignCenter()
				.Text(grade)
				.Bold()
				.FontSize(8);
		});
	}
}